### ISSUE TITLE
Pre-Launch Checklist

### ISSUE THREAD

**Issue by mgasparel** [mgasparel/blog#9]
This is a stub issue.

The intention is to curate a list of items that need to be checked before the project is considered ready for public consumption

- [ ] Remove login link from main nav
- [ ] Remove any unused files from project
- [ ] Remove any unused code or code comments from project
- [ ] Review all script includes to make sure that we are using CDN where appropriate and cache-busting taghelpers
- [ ] Check that responsive layout works flawlessly on all public-facing pages
- [ ] Ensure analytics are hooked up (AppInsights?)
- [ ] Review logging - ensure reasonable and useful use of logging
- [ ] Google Page Speed score of 90+
- [ ] Optimize HTTP headers
- [ ] Optimize images
- [ ] HTTPS everywhere
- [ ] Robots.txt
- [ ] Humans.txt
- [ ] Update Readme
